### ISSUE TITLE
Making Reasoning Matter: Measuring and Improving Faithfulness of Chain-of-Thought Reasoning

### ISSUE THREAD

**Issue by debjitpaul** [zchuz/CoT-Reasoning-Survey#2]
Our new paper on Measuring and Improving Faithfulness of Chain-of-Thought Reasoning would fit well in your survey paper list. 
Link: https://arxiv.org/abs/2402.13950 

Thank you!

**Comment by zchuz** [comment]
Thank you for providing your interesting research work; we have added it to the camera-ready version.
